if (NOT BUILD_TESTS)
    message("wasm")
    set(EMSDK_ROOT $ENV{EMSDK_ROOT})
    set(CC "/usr/local/opt/llvm/bin/clang")
    set(CXX "/usr/local/opt/llvm/bin/clang++")
    set(CMAKE_C_COMPILER "emcc")
    set(CMAKE_CXX_COMPILER "em++")
    set(CMAKE_TOOLCHAIN_FILE "${EMSDK_ROOT}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")
    set(EM_CONFIG "~/.emscripten")
    set(EMSCRIPTEN "${EMSDK_ROOT}/upstream/emscripten")
    set(ENV{EMSDK} "${EMSDK_ROOT}")
    list(APPEND CMAKE_MODULE_PATH "${EMSDK_ROOT}/upstream/emscripten/cmake")
endif ()
