if (NOT BUILD_TESTS)
    message("wasm")
    set(CC "/usr/local/opt/llvm/bin/clang")
    set(CXX "/usr/local/opt/llvm/bin/clang++")
    set(CMAKE_C_COMPILER "emcc")
    set(CMAKE_CXX_COMPILER "em++")
    set(CMAKE_TOOLCHAIN_FILE "/Users/eddielaw/Development/scripts/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")
    set(EM_CONFIG "/Users/eddielaw/.emscripten")
    set(EMSCRIPTEN "/Users/eddielaw/Development/scripts/emsdk/upstream/emscripten")
    set(ENV{EMSDK} "/Users/eddielaw/Development/scripts/emsdk")
    list(APPEND CMAKE_MODULE_PATH "/Users/eddielaw/Development/scripts/emsdk/upstream/emscripten/cmake")
endif ()
