#!/usr/bin/env bash
# temp dev script to get up and running in kf1 cljs project

nodemon --ext rs,json --exec "cargo build --target wasm32-unknown-unknown
  wasm-bindgen target/wasm32-unknown-unknown/debug/battle_rust.wasm --out-dir ./build --no-modules
  cp -rf ./build ../../public/js/battle-wasm/"
