#!/usr/bin/env bash
# temp dev script to get up and running in kf1 cljs project

nodemon --ext rs,json --exec "cargo +nightly build --target wasm32-unknown-unknown
  wasm-bindgen target/wasm32-unknown-unknown/debug/battle_rust.wasm --out-dir ./build --no-modules
  rm ./build/battle_rust.d.ts
  rm ./build/battle_rust_bg.d.ts
  cp -rf ./build/* ../js/public/game-wasm/"
