#!/usr/bin/env bash
# temp dev script to get up and running in kf1 cljs project

nodemon --ext rs --exec "wasm-pack build --target no-modules
rm ./pkg/battle_rust.d.ts
rm ./pkg/battle_rust_bg.d.ts
cp -rf ./pkg/* ../js/public/game-wasm/"
